// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piles.DbContexts;

#nullable disable

namespace Piles.Migrations
{
    [DbContext(typeof(PilesDbContext))]
    [Migration("20261006004740_AddSequenceNumber")]
    partial class AddSequenceNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Piles.Models.PileDb", b =>
                {
                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Origin", "CreatedOn");

                    b.ToTable("Piles");
                });

            modelBuilder.Entity("Piles.Models.RuminationDb", b =>
                {
                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PileCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PileOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Origin", "CreatedOn");

                    b.HasIndex("PileOrigin", "PileCreatedOn");

                    b.ToTable("Ruminations");
                });

            modelBuilder.Entity("Piles.Models.RuminationDb", b =>
                {
                    b.HasOne("Piles.Models.PileDb", "Pile")
                        .WithMany("Ruminations")
                        .HasForeignKey("PileOrigin", "PileCreatedOn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pile");
                });

            modelBuilder.Entity("Piles.Models.PileDb", b =>
                {
                    b.Navigation("Ruminations");
                });
#pragma warning restore 612, 618
        }
    }
}
