// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piles.Data;

#nullable disable

namespace Piles.Migrations
{
    [DbContext(typeof(PilesDbContext))]
    partial class PilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Piles.Data.PileDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Piles");
                });

            modelBuilder.Entity("Piles.Data.RuminationDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PileId");

                    b.ToTable("Ruminations");
                });

            modelBuilder.Entity("Piles.Data.RuminationDTO", b =>
                {
                    b.HasOne("Piles.Data.PileDTO", "Pile")
                        .WithMany("Ruminations")
                        .HasForeignKey("PileId");

                    b.Navigation("Pile");
                });

            modelBuilder.Entity("Piles.Data.PileDTO", b =>
                {
                    b.Navigation("Ruminations");
                });
#pragma warning restore 612, 618
        }
    }
}
